[package]
name = "rust-kafka-to-doris"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = "0.30.0"
clap = { version = "4.4.6", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
tokio = { version = "1.32.0", features = ["full"] }
anyhow = "1.0.75"
